title: Пока выкипают сардельки
email: info (at) suhov-aa.ru
description: >-
  Краткие байки, рассказываемые на кухне, когда стол накрыт, апперетив выпит, и все ждут, когда подадут горячее.
# baseurl: "" 
# url: "https://suhov-aa.ru" 
github_username:  Sehktel

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
port: 4001

google_analytics: UA-65128121-1
yandex_metrika: 31424498

webmaster_verifications:
  google: re7UY9qybuk1mNHj8WpOib0kIjin_boPlFAjO5TjQoA

paginate: 2
